services:
  db:
    container_name: post_dev
    image: postgres
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - .docker/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
# Helpful - docker run -it --rm postgres:latest psql -h host.docker.internal -U postgres -d postgres